#!/usr/bin/env bash

. ./scripts/utils/ansi --source-only

read -r -d '' usage <<-EOT
$(fg_col 33 USAGE):
  bootstrap [OPTIONS]

$(fg_col 33 DESCRIPTION):
  Creates test and development databases without running migrations.

$(fg_col 33 OPTIONS):
  -r    Drop databases and bootstrap.
  -h    Display usage text.
EOT

if [[ "$@" =~ "-h" ]]; then
  echo "$usage"
  exit 0
fi

while getopts "r" opt; do
  case "$opt" in
    "r")
      psql template1 -c "DROP DATABASE knodis_dev"
      psql template1 -c "DROP DATABASE knodis_test"
    ;;
  esac
done

psql template1 -c "CREATE USER patches"
psql template1 -c "CREATE DATABASE knodis_dev WITH OWNER = 'patches'"
psql template1 -c "CREATE DATABASE knodis_test WITH OWNER = 'patches'"
